= REST Cards
:toc: left
:source-highlighter: highlightjs


[[Overview]]
== Описание
Сервис предназначен для работы с объектом Card.

=== JSON schema

https://github.com/mbezrukov/alfa-p2p/blob/master/cards-json-schema[JSON schema] 

=== Параметры объекта Cards
|===
| Параметр | Тип | Описание

| id
| String
| ID карты

| direction
| String
| Направление перевода (sender - карта списания, recipient - карта зачисления, both - оба варианта)

| name
| String
| Название

| alfabank
| Boolean
| Карта Альфа-Банка? (true/false/null - да/нет/нет)

| number
| String
| Номер карты

| expirationYear
| Integer
| Год окончания срока действия

| expirationMonth
| Integer
| Месяц окончания срока действия

| cvv
| Integer
| CVV карты

| lastTransactionDate
| Date
| Дата последней транзакции (YYYY-MM-DD)

| paymentSystem
| String
| Платежная система

3+| Account

| account
| Object
| Информация по основному счету

| href
| String
| Строка запроса метода GET /accounts

| balance
| Integer
| Остаток по основному счету

3+| Currency

| currency
| Object
| Информация по валюте основного счета

| href
| String
| Строка запроса метода GET /currencies

| code
| String
| Мнемоника валюты основного счета

| description
| String
| Название валюты основного счета

3+| Bank

| bank
| Object
| ИИнформация о банке, выпустившему карту

| href
| String
| Строка запроса метода GET /banks/byCardId/{cardId}

| name 
| String
| Название банка

| color
| String
| Цвет банка

|===

=== Пример объекта
[source, json]
----
[
  {
    "id": "0000000000000001",
    "direction": "sender",
    "name": null,
    "alfabank": false,
    "number": "5154 **** 4025",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,
    "lastTransactionDate": "2015-12-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "1525050",
      "currency": {
        "href": "http://.../currency/...",
        "code": "USD",
        "description": "Доллар США"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "code": "0000001",
      "name": "Сбербанк",
      "color": "#000008"
    }
  }
]
----

[[overview-http-verbs]]
== Список методов

|===
| Метод | Описание

| <<resources-cards-get, GET /cards>>
| Получение списка карт пользователя

| <<resources-cards-byCardId, GET /cards/{cardId}>>
| Получение информации о карте пользователя по ID

| <<resources-cards-patsh, PATCH /cards/{cardId}>>
| Редактирование параметров карты в системе

|===


[[resources-cards-get]]
=== Метод GET /cards

===== Параметры заголовков запросов
|===
| Параметр | Тип | Описание 

| customerId
| String
| Mandatory +
Мнемоника пользователя и мнемоника местоположения

| applicationId
| String
| Mandatory + 
ID приложения

| mode
| String
| Mandatory +
Режим работы ("all" - карты приложения + карты Альфа-Банка)

|===


===== Параметры строки запроса
|===
| Параметр | Тип | Описание 

| verificationMethod
| String
| Optional +
Статус верификации карты ("3DSecure", "hold", "notverify") +
По умолчанию: "3DSecure" +

| deleted
| Boolean
| Optional +
Включать карты, удаленные пользователем? (true/false) +
По умолчанию: false

| blocked
| Boolean
| Optional +
Включать заблокированные карты? (true/false) +
По умолчанию: false


| active
| Boolean
| Optional +
Включать неактивные и просроченные карты? (true/false) +
По умолчанию: false

|===

==== Получение списка карт в поле карты списания
....
Дано:
  клиент находится на странице перевода.
Когда:
  клиент кликает в поле ввода карты списания.
Тогда:
  выпадает список карт: карты Альфа-Банка клиента (active = true и alfabank = true) и 
  те, с которых он ранее делал переводы (active = true и alfabank = false и direction = sender).
....
===== Example request

----
GET http://.../cards?verificationMethod=3DSecure&deleted=false&blocked=false&active=true&direction=sender
----

===== Example response
[source, json]
----
[
  {
    "id": "0000000000000001",
    "direction": "sender",
    "name": null,
    "alfabank": true,
    "number": "5154 **** 4025",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,
    "lastTransactionDate": "2015-01-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "1525050",
      "currency": {
        "href": "http://.../currency/...",
        "code": "RUR",
        "description": "Рубль"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "code": "0000001",
      "name": "Альфа-Банк",
      "color": "#000007"
    }
  },
  {
    "id": "0000000000000002",
    "direction": "sender",
    "name": null,
    "alfabank": false,
    "number": "5154 **** 4040",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,    
    "lastTransactionDate": "2015-01-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "25000",
      "currency": {
        "href": "http://.../currency/...",
        "code": "RUR",
        "description": "Рубль"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "code": "0000002",
      "name": "Сбербанк",
      "color": "#000008"
    }
  }
]
----

==== Получение списка карт в поле карты зачисления
....
Дано:
  клиент находится на странице перевода.
Когда:
  клиент кликает в поле ввода карты зачисления.
Тогда:
  выпадает список карт: карты Альфа-Банка клиента (active = true и alfabank = true) и 
  те, на которые он ранее делал переводы (active = true и alfabank = false и direction = recipient).
....
===== Example request
----
GET http://.../cards?verificationMethod=3DSecure&deleted=false&blocked=false&active=true&direction=recipient
----
===== Example response
[source, json]
----
[
  {
    "id": "0000000000000003",
    "direction": "recipient",
    "name": null,
    "alfabank": true,
    "number": "5154 **** 4052",
    "expirationYear": "15",
    "expirationMonth": "07",
    "lastTransactionDate": "2015-01-15",
    "cvv": null,
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "100050",
      "currency": {
        "href": "http://.../currency/...",
        "code": "RUR",
        "description": "Рубль"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "code": "0000001",
      "name": "Альфа-Банк",
      "color": "#000007"
    }
  },
  {
    "id": "0000000000000004",
    "direction": "recipient",
    "name": null,
    "alfabank": false,
    "number": "5154 **** 4070",
    "expirationYear": "15",
    "expirationMonth": "07",
    "cvv": null,
    "lastTransactionDate": "2015-01-15",
    "paymentSystem": "MC",
    "account": {
      "href": "http://.../accounts/...",
      "balance": "5000050",
      "currency": {
        "href": "http://.../currency/...",
        "code": "USD",
        "description": "Доллар США"
      }
    },
    "bank": {
      "href": "http://.../banks/...",
      "code": "0000002",
      "name": "Сбербанк",
      "color": "#000008"
    }
  }
]
----

[[resources-cards-byCardId]]
=== Метод GET /cards/{cardId}


===== Параметры заголовков запросов
|===
| Параметр | Тип | Описание 

| customerId
| String
| Mandatory +
Мнемоника пользователя и мнемоника местоположения


| applicationId
| String
| Mandatory +
ID приложения


|===


===== Параметры строки запроса
|===
| Параметр | Тип | Описание 

| Id
| String
| Mandatory +
ID карты


|===


==== Получение параметров заданной карты 
....
Клиент получает все данные по своей карте (id = 0000000000000003)
....
===== Example request
----
GET http://.../cards/0000000000000003
----
===== Example response
[source, json]
----
{
  "id": "0000000000000003",
  "direction": "recipient",
  "name": null,
  "alfabank": true,
  "number": "5154 **** 4052",
  "expirationYear": "15",
  "expirationMonth": "07",
  "cvv": null,
  "lastTransactionDate": "2015-01-15",
  "paymentSystem": "MC",
  "account": {
    "href": "http://.../accounts/...",
    "balance": "100050",
    "currency": {
      "href": "http://.../currency/...",
      "code": "RUR",
      "description": Рубль"
    }
  },
  "bank": {
    "href": "http://.../banks/...",
    "code": "0000001",
    "name": "Альфа-Банк",
    "color": "#000007"
  }
}
----


[[resources-cards-patch]]
=== Метод PATCH /cards/{cardId}

===== Параметры заголовков запросов
|===
| Параметр | Тип | Описание 

| customerId
| String
| Mandatory +
Мнемоника пользователя и мнемоника местоположения


| applicationId
| String
| Mandatory +
ID приложения


|===


===== Параметры строки запроса
|===
| Параметр |  Тип | Описание 

| Id
| String
| Mandatory +
ID карты


|===


==== Редактирование названия карты
....
Дано:
  клиент кликает на псевдоссылку с названием карты.
Когда:
  вводит новое название карты (name = 0000000000000001)
Тогда:
  сохраняется новое название карты.
....
===== Example request
----
PATCH http://.../cards/0000000000000001
----
===== Example response
----
HTTP/1.1 200 OK
----
